In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import csv
import os

# Input and output file paths
input_train_file = "/kaggle/input/detecting-reversal-points-in-us-equities/competition_data/train.csv"
output_train_file = "modified_train.csv"
input_test_file = "/kaggle/input/detecting-reversal-points-in-us-equities/competition_data/test.csv"
output_test_file = "modified_test.csv"

# Function to process the CSV
def process_csv(input_path, output_path):
    with open(input_path, 'r', newline='') as infile, open(output_path, 'w', newline='') as outfile:
        reader = csv.reader(infile)
        writer = csv.writer(outfile)
        
        # Read the header row
        header = next(reader)
        
        # Identify indices of columns with specific prefixes
        happens_within_indices = [i for i, col in enumerate(header) if col.startswith('happens_within')]
        crossing_above_indices = [i for i, col in enumerate(header) if col.startswith('cross_threshold_from_above')]
        crossing_below_indices = [i for i, col in enumerate(header) if col.startswith('cross_threshold_from_below')]
        trending_down_indices = [i for i, col in enumerate(header) if col.startswith('trending_down_and_above')]
        trending_up_indices = [i for i, col in enumerate(header) if col.startswith('trending_up_and_below')]
        troughs_indices = [i for i, col in enumerate(header) if col.startswith('troughs')]
        peaks_indices = [i for i, col in enumerate(header) if col.startswith('peaks')]
        
        # Keep columns that are not any of the specified prefixes
        other_indices = [i for i, col in enumerate(header) if not (
            col.startswith('happens_within') or 
            col.startswith('occurs_within') or 
            col.startswith('cross_threshold_from_above') or 
            col.startswith('cross_threshold_from_below') or
            col.startswith('trending_down_and_above') or
            col.startswith('trending_up_and_below') or
            col.startswith('troughs') or
            col.startswith('zone') or
            col.startswith('peaks')
        )]
        
        # Create new header: keep other columns, add new columns for counts
        new_header = [header[i] for i in other_indices] + [
            'happens_within',  
            'cross_threshold_from_above', 
            'cross_threshold_from_below',
            'trending_down_and_above',
            'trending_up_and_below',
            'troughs',
            'peaks'
        ]
        writer.writerow(new_header)
        
        # Process each data row
        for row in reader:
            # Count "True" values in each set of columns
            happens_within_count = sum(1 for i in happens_within_indices if row[i] == 'True')
            crossing_above_count = sum(1 for i in crossing_above_indices if row[i] == 'True')
            crossing_below_count = sum(1 for i in crossing_below_indices if row[i] == 'True')
            trending_down_count = sum(1 for i in trending_down_indices if row[i] == 'True')
            trending_up_count = sum(1 for i in trending_up_indices if row[i] == 'True')
            troughs_count = sum(1 for i in troughs_indices if row[i] == 'True')
            peaks_count = sum(1 for i in peaks_indices if row[i] == 'True')
            
            # Create new row: keep other columns, add counted columns
            new_row = [row[i] for i in other_indices] + [
                str(happens_within_count), 
                str(crossing_above_count), 
                str(crossing_below_count),
                str(trending_down_count),
                str(trending_up_count),
                str(troughs_count),
                str(peaks_count)
            ]
            writer.writerow(new_row)

# Execute the processing
process_csv(input_train_file, output_train_file)
print(f"Processed CSV saved as {output_train_file}")
process_csv(input_test_file, output_test_file)
print(f"Processed CSV saved as {output_test_file}")

NameError: name 'output_file' is not defined

In [4]:
# import csv
# import os

# # Input and output file paths
# input_file = "/home/hp/Study/Code/AI/Equity_time_series_high_low_detector/detecting-reversal-points-in-us-equities/competition_data/test.csv"
# output_file = "modified_test.csv"

# # Function to process the CSV
# def process_csv(input_path, output_path):
#     with open(input_path, 'r', newline='') as infile, open(output_path, 'w', newline='') as outfile:
#         reader = csv.reader(infile)
#         writer = csv.writer(outfile)
        
#         # Read the header row
#         header = next(reader)
        
#         # Identify indices of columns with specific prefixes
#         happens_within_indices = [i for i, col in enumerate(header) if col.startswith('happens_within')]
#         crossing_above_indices = [i for i, col in enumerate(header) if col.startswith('cross_threshold_from_above')]
#         crossing_below_indices = [i for i, col in enumerate(header) if col.startswith('cross_threshold_from_below')]
#         trending_down_indices = [i for i, col in enumerate(header) if col.startswith('trending_down_and_above')]
#         trending_up_indices = [i for i, col in enumerate(header) if col.startswith('trending_up_and_below')]
#         troughs_indices = [i for i, col in enumerate(header) if col.startswith('troughs')]
#         peaks_indices = [i for i, col in enumerate(header) if col.startswith('peaks')]
        
#         # Keep columns that are not any of the specified prefixes
#         other_indices = [i for i, col in enumerate(header) if not (
#             col.startswith('happens_within') or 
#             col.startswith('occurs_within') or 
#             col.startswith('cross_threshold_from_above') or 
#             col.startswith('cross_threshold_from_below') or
#             col.startswith('trending_down_and_above') or
#             col.startswith('trending_up_and_below') or
#             col.startswith('troughs') or
#             col.startswith('zone') or
#             col.startswith('peaks')
#         )]
        
#         # Create new header: keep other columns, add new columns for counts
#         new_header = [header[i] for i in other_indices] + [
#             'happens_within', 
#             'cross_threshold_from_above', 
#             'cross_threshold_from_below',
#             'trending_down_and_above',
#             'trending_up_and_below',
#             'troughs',
#             'peaks'
#         ]
#         writer.writerow(new_header)
        
#         # Process each data row
#         for row in reader:
#             # Count "True" values in each set of columns
#             happens_within_count = sum(1 for i in happens_within_indices if row[i] == 'True')
#             crossing_above_count = sum(1 for i in crossing_above_indices if row[i] == 'True')
#             crossing_below_count = sum(1 for i in crossing_below_indices if row[i] == 'True')
#             trending_down_count = sum(1 for i in trending_down_indices if row[i] == 'True')
#             trending_up_count = sum(1 for i in trending_up_indices if row[i] == 'True')
#             troughs_count = sum(1 for i in troughs_indices if row[i] == 'True')
#             peaks_count = sum(1 for i in peaks_indices if row[i] == 'True')
            
#             # Create new row: keep other columns, add counted columns
#             new_row = [row[i] for i in other_indices] + [
#                 str(happens_within_count), 
#                 str(crossing_above_count), 
#                 str(crossing_below_count),
#                 str(trending_down_count),
#                 str(trending_up_count),
#                 str(troughs_count),
#                 str(peaks_count)
#             ]
#             writer.writerow(new_row)

# # Execute the processing
# process_csv(input_file, output_file)
# print(f"Processed CSV saved as {output_file}")

In [3]:
import pandas as pd

def sort_csv_by_column(file_path, column_name):
    # Read CSV
    df = pd.read_csv(file_path)

    # Sort by column 't'
    df_sorted = df.sort_values(by=column_name)

    # Write back to same file (overwrite)
    df_sorted.to_csv(file_path, index=False)

    print(f"File '{file_path}' has been sorted by column '{column_name}' and overwritten.")

sort_csv_by_column('modified_train.csv', 't')
sort_csv_by_column('modified_test.csv', 't')

File 'modified_train.csv' has been sorted by column 't' and overwritten.
File 'modified_test.csv' has been sorted by column 't' and overwritten.


In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, f1_score, balanced_accuracy_score, matthews_corrcoef
from sklearn.utils.class_weight import compute_class_weight
import xgboost as xgb
import time

# File path for train
input_train_file = "modified_train.csv"
input_test_file = "modified_test.csv"

# Load the CSV into a Pandas DataFrame
df_train = pd.read_csv(input_train_file)
df_test = pd.read_csv(input_test_file)

In [5]:
df_train['class_label'] = df_train['class_label'].replace({
    'HH': 'H',
    'LH': 'H',
    'LL': 'L',
    'HL': 'L'
}).where(df_train['class_label'].isin(['HH', 'LH', 'LL', 'HL']), other='N')

In [6]:
import pandas as pd

print("Descriptive statistics:")
print(df_train.describe(include='all'))   

print("Info & null counts:")
print(df_train.info())
print("\nMissing values per column:")
print(df_train.isnull().sum())

print("Unique values per column:")
for col in df_train.columns:
    print(f"{col}: {df_train[col].nunique()} unique values")

print("Sample categories per column:")
for col in df_train.select_dtypes(include='object').columns:
    print(f"{col}: {df_train[col].unique()[:10]}")  

Descriptive statistics:
           train_id    ticker_id           t     momentum        ratio  \
count   1932.000000  1932.000000        1932  1932.000000  1932.000000   
unique          NaN          NaN         460          NaN          NaN   
top             NaN          NaN  2024-01-12          NaN          NaN   
freq            NaN          NaN           6          NaN          NaN   
mean     965.500000     3.500000         NaN    99.992433   100.003231   
std      557.864679     1.708267         NaN     0.766347     1.037714   
min        0.000000     1.000000         NaN    96.087990    95.327515   
25%      482.750000     2.000000         NaN    99.573017    99.402484   
50%      965.500000     3.500000         NaN    99.985227    99.981954   
75%     1448.250000     5.000000         NaN   100.444782   100.634551   
max     1931.000000     6.000000         NaN   102.465023   103.870229   

        sm_momentum     sm_ratio class_label  happens_within  \
count   1932.000000  19

In [7]:
import pandas as pd

print("Descriptive statistics:")
print(df_test.describe(include='all'))   

print("Info & null counts:")
print(df_test.info())
print("\nMissing values per column:")
print(df_test.isnull().sum())

print("Unique values per column:")
for col in df_test.columns:
    print(f"{col}: {df_test[col].nunique()} unique values")

print("Sample categories per column:")
for col in df_test.select_dtypes(include='object').columns:
    print(f"{col}: {df_test[col].unique()[:10]}") 

Descriptive statistics:
                id   ticker_id           t    momentum       ratio  \
count   828.000000  828.000000         828  828.000000  828.000000   
unique         NaN         NaN         410         NaN         NaN   
top            NaN         NaN  2023-06-30         NaN         NaN   
freq           NaN         NaN           5         NaN         NaN   
mean    413.500000    3.500000         NaN   99.978878   99.997910   
std     239.167305    1.708857         NaN    0.768823    1.088092   
min       0.000000    1.000000         NaN   96.513556   95.641552   
25%     206.750000    2.000000         NaN   99.500658   99.405569   
50%     413.500000    3.500000         NaN   99.975093  100.028616   
75%     620.250000    5.000000         NaN  100.484466  100.646528   
max     827.000000    6.000000         NaN  102.504383  103.894367   

        sm_momentum    sm_ratio  happens_within  cross_threshold_from_above  \
count    828.000000  828.000000      828.000000         

In [8]:
df_train.head()

train_id  ticker_id           t    momentum       ratio  sm_momentum  \
0       775          6  2023-04-03   99.999622  100.153223    99.403022   
1       410          1  2023-04-03   99.131989  100.162810    99.942529   
2      1363          4  2023-04-03   99.657066  100.054925   100.764058   
3       490          2  2023-04-03  100.065645  100.174210    99.003064   
4       364          3  2023-04-04  100.859582  101.387954   102.188969   

     sm_ratio class_label  happens_within  cross_threshold_from_above  \
0   99.570105           N              20                           0   
1   99.922969           N              20                           0   
2   99.579857           H              20                           0   
3  100.347891           N              20                           0   
4   99.440955           N               2                           0   

   cross_threshold_from_below  trending_down_and_above  trending_up_and_below  \
0                           0                        0                      0   
1                           0                        0                      0   
2                           0                        0                      0   
3                           0                        0                      0   
4                           0                        0                      0   

   troughs  peaks  
0        0      0  
1        0      0  
2        0      0  
3        0      0  
4        0      0

In [9]:
df_test.head()

id  ticker_id           t    momentum       ratio  sm_momentum  \
0  199          5  2023-04-03   98.028059  100.167714    99.010811   
1  753          3  2023-04-03  101.724160  101.814890   102.358914   
2  316          5  2023-04-04   97.921661   99.677934    99.071748   
3  313          1  2023-04-04   99.166349  100.040334    99.746758   
4  536          4  2023-04-05   99.408127   99.734170   100.738871   

     sm_ratio  happens_within  cross_threshold_from_above  \
0  100.347891              20                           0   
1   99.318084              20                           0   
2  100.292253               2                           0   
3   99.826205               2                           0   
4   99.712689             104                           0   

   cross_threshold_from_below  trending_down_and_above  trending_up_and_below  \
0                           0                        0                      0   
1                           0                        0                      0   
2                           0                        0                      0   
3                           0                        0                      0   
4                           0                        0                      0   

   troughs  peaks  
0        0      0  
1        0      0  
2        0      0  
3        0      0  
4        0      2

In [10]:
df_001=df_train[df_train['ticker_id']==1]
df_002=df_train[df_train['ticker_id']==2]
df_003=df_train[df_train['ticker_id']==3]
df_004=df_train[df_train['ticker_id']==4]
df_005=df_train[df_train['ticker_id']==5]
df_006=df_train[df_train['ticker_id']==6]

In [11]:
except_features = ['train_id', 'ticker_id', 't', 'class_label']

dfs = [df_001, df_002, df_003, df_004, df_005, df_006]

feature_stats = {}

for i, df in enumerate(dfs, start=1):
    cols_to_scale = [col for col in df.columns if col not in except_features]
    
    means = df[cols_to_scale].mean()
    stds = df[cols_to_scale].std(ddof=0)
    feature_stats[i] = {'mean': means, 'std': stds}

    df[cols_to_scale] = (df[cols_to_scale] - means) / stds

    globals()[f"df_{i:03}"] = df

In [12]:
import plotly.graph_objects as go
import pandas as pd

x = df_001['t'].tolist()
y1 = df_001['ratio'].tolist()
y2 = df_001['sm_ratio'].tolist()
y3 = df_001['momentum'].tolist()
y4 = df_001['sm_momentum'].tolist()
y5 = df_001['happens_within'].tolist()
y7 = df_001['cross_threshold_from_above'].tolist()
y8 = df_001['cross_threshold_from_below'].tolist()
y9 = df_001['trending_down_and_above'].tolist()
y10 = df_001['trending_up_and_below'].tolist()
y11 = df_001['troughs'].tolist()
y12 = df_001['peaks'].tolist()
label = df_001['class_label'].tolist()

fig = go.Figure()

# Plot all traces
fig.add_trace(go.Scatter(x=x, y=y1, mode='lines', name='Momentum', line=dict(color='blue')))
fig.add_trace(go.Scatter(x=x, y=y2, mode='lines', name='Smoothed Momentum', line=dict(color='orange')))
# fig.add_trace(go.Scatter(x=x, y=y3, mode='lines', name='Ratio', line=dict(color='green')))
# fig.add_trace(go.Scatter(x=x, y=y4, mode='lines', name='Smoothed Ratio', line=dict(color='purple')))
# fig.add_trace(go.Scatter(x=x, y=y5, mode='lines', name='Happens Within', line=dict(color='cyan')))
# fig.add_trace(go.Scatter(x=x, y=y7, mode='lines', name='Cross Threshold From Above', line=dict(color='yellow')))
# fig.add_trace(go.Scatter(x=x, y=y8, mode='lines', name='Cross Threshold From Below', line=dict(color='lime')))
# fig.add_trace(go.Scatter(x=x, y=y9, mode='lines', name='Trending Down And Above', line=dict(color='orange')))
# fig.add_trace(go.Scatter(x=x, y=y10, mode='lines', name='Trending Up And Below', line=dict(color='lightgreen')))
# fig.add_trace(go.Scatter(x=x, y=y11, mode='lines', name='Troughs', line=dict(color='brown')))
# fig.add_trace(go.Scatter(x=x, y=y12, mode='lines', name='Peaks', line=dict(color='pink')))

# Plot H / L labels as text markers
for xi, yi, lbl in zip(x, y11, label):
    if lbl == 'H':
        fig.add_trace(go.Scatter(
            x=[xi], y=[yi + 0.1],  # small offset above the line
            mode='text', text=['H'],
            textfont=dict(color='red', size=12), showlegend=False
        ))
    elif lbl == 'L':
        fig.add_trace(go.Scatter(
            x=[xi], y=[yi - 0.1],  # small offset below the line
            mode='text', text=['L'],
            textfont=dict(color='red', size=12), showlegend=False
        ))

# Layout - autoscale y-axis
fig.update_layout(
    title='Momentum and Smoothed Momentum with H/L Labels',
    xaxis_title='Time (t)',
    yaxis_title='Momentum / Ratio / Events',
    template='plotly_dark',
    xaxis=dict(rangeslider=dict(visible=True)),  # Scrollable range slider
    yaxis=dict(autorange=True),                  # Auto-scale y-axis based on all traces
    hovermode='x unified'
)

fig.show()


In [13]:
except_features = ['train_id', 'ticker_id', 't', 'class_label']

dfs = [df_001, df_002, df_003, df_004, df_005, df_006]

max_lag = 2

for i, df in enumerate(dfs, start=1):
    cols_to_lag = [col for col in df.columns if col not in except_features]
    
    for col in cols_to_lag:
        for lag in range(1, max_lag + 1):
            df[f"{col}_lag{lag}"] = df[col].shift(lag)
    
    globals()[f"df_{i:03}"] = df

# AdaBoost

In [14]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report, balanced_accuracy_score

n_estimators = 50
except_features = ['train_id', 'ticker_id', 't', 'class_label']

dfs = [df_001, df_002, df_003, df_004, df_005, df_006]

class_mapping = {'N': 0, 'H': 1, 'L': 2}
inverse_class_mapping = {v: k for k, v in class_mapping.items()}

models = {}

for df in dfs:
    ticker_id = df['ticker_id'].iloc[0]

    df_HL = df[df['class_label'].isin(['H', 'L'])]
    df_HL_oversampled = pd.concat([df_HL] * 4, ignore_index=True)
    n_hl = 2*len(df_HL_oversampled)
    df_N = df[df['class_label'] == 'N']
    df_N_sampled = df_N.sample(n=n_hl, replace=False)  

    # Combine and sort by time
    train_df = pd.concat([df_HL_oversampled, df_N_sampled]).sort_values('t').reset_index(drop=True)


    X_train = train_df.drop(except_features, axis=1)
    y_train = train_df['class_label']

    base_estimator = DecisionTreeClassifier(max_depth=4, random_state=None)
    ada = AdaBoostClassifier(estimator=base_estimator, n_estimators=n_estimators, random_state=42)

    X_train = X_train.fillna(0)
    ada.fit(X_train, y_train)

    models[ticker_id] = ada

    validation_set_size =  3*n_hl
    val_df = df.sample(n=validation_set_size, replace=True, random_state=99)
    X_val = val_df.drop(except_features, axis=1)
    y_val = val_df['class_label']

    X_val = X_val.fillna(0)
    y_pred = ada.predict(X_val)

    # Confusion Matrix
    cm = confusion_matrix(y_val, y_pred, labels=['H', 'L', 'N'])
    print(f"Confusion Matrix for Ticker {ticker_id}:\n{cm}\n")

    # Classification Report
    cr = classification_report(y_val, y_pred, labels=['H', 'L', 'N'])
    print(f"Classification Report for Ticker {ticker_id}:\n{cr}")

    # Balanced Accuracy
    bal_acc = balanced_accuracy_score(y_val, y_pred)
    print(f"Balanced Accuracy for Ticker {ticker_id}: {bal_acc:.4f}\n")


Confusion Matrix for Ticker 1:
[[ 17   0   0]
 [  0   8   0]
 [  4   4 399]]

Classification Report for Ticker 1:
              precision    recall  f1-score   support

           H       0.81      1.00      0.89        17
           L       0.67      1.00      0.80         8
           N       1.00      0.98      0.99       407

    accuracy                           0.98       432
   macro avg       0.83      0.99      0.89       432
weighted avg       0.99      0.98      0.98       432

Balanced Accuracy for Ticker 1: 0.9934

Confusion Matrix for Ticker 2:
[[  6   0   0]
 [  0   4   0]
 [  0   0 326]]

Classification Report for Ticker 2:
              precision    recall  f1-score   support

           H       1.00      1.00      1.00         6
           L       1.00      1.00      1.00         4
           N       1.00      1.00      1.00       326

    accuracy                           1.00       336
   macro avg       1.00      1.00      1.00       336
weighted avg       1.00  

In [15]:
import pandas as pd
import numpy as np
import os

# Load test data
test_df = pd.read_csv('modified_test.csv')

# Create index-to-feature mapping from columns
feature_mapping = {idx: col for idx, col in enumerate(test_df.columns)}

except_features_test = ['id', 'ticker_id', 't']
max_lag = 2

# Define lag feature order (same as training)
lag_feature_order = [col for col in test_df.columns if col not in except_features_test]

# Initialize lag buffers for each ticker_id
lag_buffers = {
    tid: {col: [] for col in lag_feature_order} for tid in range(1, 7)
}

# Assume these are already loaded from training
# feature_stats = {ticker_id: {'mean': ..., 'std': ...}, ...}
# models = {ticker_id: [list of trained decision trees], ...}

# Class label mappings
class_mapping = {'N': 0, 'H': 1, 'L': 2}
inverse_class_mapping = {v: k for k, v in class_mapping.items()}

def forest_predict(models, X, class_mapping, inverse_class_mapping):
    """
    Predict using a custom ensemble of trees with majority voting.
    """
    preds = np.array([
        [class_mapping[label] for label in tree.predict(X)]
        for tree in models
    ])
    final_preds = []
    for i in range(X.shape[0]):
        counts = np.bincount(preds[:, i])
        majority_class_int = np.argmax(counts)
        final_preds.append(inverse_class_mapping[majority_class_int])
    return final_preds

predictions = []

for idx, row in test_df.iterrows():
    ticker = int(row['ticker_id'])
    row_id = row['id']

    if ticker not in models or ticker not in feature_stats:
        print(f"Skipping row id {row_id} due to missing model or stats for ticker {ticker}")
        continue

    stats = feature_stats[ticker]
    model = models[ticker]

    # Scale features
    scaled_row = {}
    for idx_col, col in feature_mapping.items():
        if col not in except_features_test:
            val = row[col]
            mean = stats['mean'].get(col, 0)
            std = stats['std'].get(col, 1)
            if pd.isna(val):
                val = mean  # simple imputation
            scaled_row[col] = (val - mean) / std if std != 0 else 0

    # Create lag features
    lag_features = {}
    for col in lag_feature_order:
        for lag in range(1, max_lag + 1):
            if len(lag_buffers[ticker][col]) >= lag:
                lag_features[f'{col}_lag{lag}'] = lag_buffers[ticker][col][-lag]
            else:
                lag_features[f'{col}_lag{lag}'] = 0

    # Prepare input feature vector following the order used in training
    input_features = []
    for col in lag_feature_order:
        input_features.append(scaled_row[col])
    for col in lag_feature_order:
        for lag in range(1, max_lag + 1):
            input_features.append(lag_features[f'{col}_lag{lag}'])

    input_array = np.array(input_features).reshape(1, -1)

    # Predict using the custom forest predictor
    pred = forest_predict(model, input_array, class_mapping, inverse_class_mapping)[0]

    predictions.append({'id': row_id, 'class_label': pred})

    # Update the lag buffers
    for col in lag_feature_order:
        lag_buffers[ticker][col].append(scaled_row[col])
        if len(lag_buffers[ticker][col]) > max_lag:
            lag_buffers[ticker][col].pop(0)

# Save predictions
os.makedirs('predictions', exist_ok=True)
pd.DataFrame(predictions).to_csv('predictions/adaboost_predictions.csv', index=False)


# Custom ensemble

In [16]:
import numpy as np
import pandas as pd
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, balanced_accuracy_score
from collections import Counter

def build_small_nn(input_dim, mid_dim=16, out_dim=3):
    model = keras.Sequential([
        keras.layers.Dense(mid_dim, activation='relu', input_shape=(input_dim,)),
        keras.layers.Dense(out_dim, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

# Ensemble configuration
n_ensemble = 30        # models per ticker
n_cols = 16               # input features per member
n_rows = 40               # rows per member
mid_dim = 8           # hidden size
epochs = 10
except_features = ['train_id', 'ticker_id', 't', 'class_label']
class_mapping = {'N': 0, 'H': 1, 'L': 2}
inverse_class_mapping = {v: k for k, v in class_mapping.items()}

dfs = [df_001, df_002, df_003, df_004, df_005, df_006]

models = {}
col_subspaces = {}
weights = {}

for df in dfs:
    ticker_id = df['ticker_id'].iloc[0]
    # Imbalance handling (optional, edit repeat factor as needed)
    df_HL = df[df['class_label'].isin(['H', 'L'])]
    df_HL_oversampled = pd.concat([df_HL], ignore_index=True)  # upsample HL
    n_hl = 2 * len(df_HL_oversampled)
    df_N = df[df['class_label'] == 'N']
    df_N_sampled = df_N.sample(n=n_hl, replace=False)  # downsample N
    
    # Merge and prep X/y
    train_df = pd.concat([df_HL_oversampled, df_N_sampled]).sort_values('t').reset_index(drop=True)
    y_full = train_df['class_label'].map(class_mapping).values
    candidate_cols = [col for col in train_df.columns if col not in except_features]

    ensemble = []
    subspaces = []
    val_scores = []

    # Build ensemble: for each NN, sample rows/cols
    for i in range(n_ensemble):
        chosen_cols = np.random.choice(candidate_cols, size=n_cols, replace=False)
        subspaces.append(chosen_cols)
        # Draw bootstrap row samples
        rows = np.random.choice(len(train_df), size=n_rows, replace=True)
        X_boot = train_df.iloc[rows][chosen_cols].fillna(0).values
        y_boot = y_full[rows]

        # If any class in y_boot has <2, use unstratified split (prevents ValueError)
        class_counts = Counter(y_boot)
        if min(class_counts.values()) < 2:
            X_train, X_val, y_train, y_val = train_test_split(X_boot, y_boot, test_size=0.2)
        else:
            X_train, X_val, y_train, y_val = train_test_split(X_boot, y_boot, test_size=0.2, stratify=y_boot)

        # Build, train, evaluate
        model = build_small_nn(input_dim=n_cols, mid_dim=mid_dim, out_dim=3)
        model.fit(X_train, y_train, epochs=epochs, batch_size=5, verbose=0)
        val_pred = np.argmax(model.predict(X_val, verbose=0), axis=1)
        bal_acc = balanced_accuracy_score(y_val, val_pred)
        val_scores.append(bal_acc)
        ensemble.append(model)

    col_subspaces[ticker_id] = subspaces
    models[ticker_id] = ensemble
    # Normalize validation balanced accuracy for weighted voting
    arr = np.array(val_scores)
    arr = arr / (arr.sum() + 1e-12)
    weights[ticker_id] = arr.tolist()

    # --- ENSEMBLE VALIDATION ---
    # Sample a large validation set from the original df (not train_df)
    validation_set_size = 3 * n_hl
    val_df = df.sample(n=validation_set_size, replace=True, random_state=99)
    X_val_full = val_df.drop(except_features, axis=1).fillna(0)
    y_val_full = val_df['class_label'].map(class_mapping).values

    # For each row, build ensemble prediction
    y_pred_full = []
    for _, row in X_val_full.iterrows():
        weighted_probs = np.zeros(3)
        for model, subcols, w in zip(ensemble, subspaces, weights[ticker_id]):
            input_features = []
            for col in subcols:
                # If missing, fill with 0
                input_features.append(row[col] if col in row else 0)
            input_array = np.array(input_features, dtype=np.float32).reshape(1, -1)
            prob = model.predict(input_array, verbose=0)[0]
            weighted_probs += w * prob
        pred_class_idx = int(np.argmax(weighted_probs))
        y_pred_full.append(pred_class_idx)

    # Print metrics
    cm = confusion_matrix(y_val_full, y_pred_full, labels=[1, 2, 0])
    print(f"Confusion Matrix for Ticker {ticker_id}:\n{cm}\n")
    cr = classification_report(y_val_full, y_pred_full, labels=[1, 2, 0], target_names=['H', 'L', 'N'])
    print(f"Classification Report for Ticker {ticker_id}:\n{cr}")
    bal_acc = balanced_accuracy_score(y_val_full, y_pred_full)
    print(f"Balanced Accuracy for Ticker {ticker_id}: {bal_acc:.4f}\n")

print('Finished NN ensemble training and validation!')

2025-10-05 10:49:40.219042: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


Confusion Matrix for Ticker 1:
[[ 0  0  3]
 [ 0  0  2]
 [ 4  0 99]]

Classification Report for Ticker 1:
              precision    recall  f1-score   support

           H       0.00      0.00      0.00         3
           L       0.00      0.00      0.00         2
           N       0.95      0.96      0.96       103

    accuracy                           0.92       108
   macro avg       0.32      0.32      0.32       108
weighted avg       0.91      0.92      0.91       108

Balanced Accuracy for Ticker 1: 0.3204

Confusion Matrix for Ticker 2:
[[ 0  0  2]
 [ 0  1  1]
 [ 7  6 67]]

Classification Report for Ticker 2:
              precision    recall  f1-score   support

           H       0.00      0.00      0.00         2
           L       0.14      0.50      0.22         2
           N       0.96      0.84      0.89        80

    accuracy                           0.81        84
   macro avg       0.37      0.45      0.37        84
weighted avg       0.91      0.81      0.86

In [17]:
import pandas as pd
import numpy as np
import os

test_df = pd.read_csv('modified_test.csv')
except_features_test = ['id', 'ticker_id', 't']
max_lag = 2
lag_feature_order = [col for col in test_df.columns if col not in except_features_test]
class_mapping = {'N': 0, 'H': 1, 'L': 2}
inverse_class_mapping = {v: k for k, v in class_mapping.items()}

# Prepare lag buffers
lag_buffers = {tid: {col: [] for col in lag_feature_order} for tid in range(1, 7)}

# Prepare output
predictions = []

# Group test data by ticker for efficiency
for ticker, group in test_df.groupby('ticker_id'):
    if (ticker not in models or ticker not in feature_stats or
        ticker not in col_subspaces or ticker not in weights):
        for row_id in group['id']:
            print(f"Skipping row id {row_id} due to missing ensemble/model/stats for ticker {ticker}")
        continue

    stats = feature_stats[ticker]
    ensemble_models = models[ticker]
    model_cols = col_subspaces[ticker]
    model_weights = weights[ticker]

    # Precompute scaled features and lag features for all rows
    scaled_rows = []
    lag_features_list = []
    for idx, row in group.iterrows():
        scaled_row = {}
        for col in lag_feature_order:
            val = row.get(col, np.nan)
            mean = stats['mean'].get(col, 0)
            std = stats['std'].get(col, 1)
            if pd.isna(val):
                val = mean
            scaled_row[col] = (val - mean) / std if std != 0 else 0
        scaled_rows.append(scaled_row)

        lag_features = {}
        for col in lag_feature_order:
            for lag in range(1, max_lag + 1):
                key = f'{col}_lag{lag}'
                if len(lag_buffers[ticker][col]) >= lag:
                    lag_features[key] = lag_buffers[ticker][col][-lag]
                else:
                    lag_features[key] = 0
        lag_features_list.append(lag_features)

        # Update lag buffers for next row
        for col in lag_feature_order:
            lag_buffers[ticker][col].append(scaled_row.get(col, 0))
            if len(lag_buffers[ticker][col]) > max_lag:
                lag_buffers[ticker][col].pop(0)

    # For each model in the ensemble, build its input matrix for all rows
    all_weighted_probs = np.zeros((len(group), 3))
    for model, subcols, w in zip(ensemble_models, model_cols, model_weights):
        input_matrix = []
        for scaled_row, lag_features in zip(scaled_rows, lag_features_list):
            input_features = []
            for col in subcols:
                if col in scaled_row:
                    input_features.append(scaled_row[col])
                elif col in lag_features:
                    input_features.append(lag_features[col])
                else:
                    input_features.append(0)
            input_matrix.append(input_features)
        input_matrix = np.array(input_matrix, dtype=np.float32)
        probs = model.predict(input_matrix, verbose=0)
        all_weighted_probs += w * probs

    # Final prediction for each row in this ticker group
    for i, (idx, row) in enumerate(group.iterrows()):
        final_class_idx = int(np.argmax(all_weighted_probs[i]))
        final_class = inverse_class_mapping[final_class_idx]
        predictions.append({'id': row['id'], 'class_label': final_class})

# Save predictions
os.makedirs('predictions', exist_ok=True)
pd.DataFrame(predictions).to_csv('predictions/nn_ensemble_predictions.csv', index=False)

# XgBoost

In [18]:
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, classification_report, balanced_accuracy_score
import pandas as pd
import numpy as np

n_estimators = 30
except_features = ['train_id', 'ticker_id', 't', 'class_label']

dfs = [df_001, df_002, df_003, df_004, df_005, df_006]

class_mapping = {'N': 0, 'H': 1, 'L': 2}
inverse_class_mapping = {v: k for k, v in class_mapping.items()}

models = {}

for df in dfs:
    ticker_id = df['ticker_id'].iloc[0]

    # Oversample HL by repeating 2 times
    df_HL = df[df['class_label'].isin(['H', 'L'])]
    df_HL_oversampled = pd.concat([df_HL] * 2, ignore_index=True)

    # Undersample N to match twice the oversampled HL size
    n_hl = 3 * len(df_HL_oversampled)
    df_N = df[df['class_label'] == 'N']
    df_N_sampled = df_N.sample(n=n_hl, replace=False)

    # Combine and sort by time
    train_df = pd.concat([df_HL_oversampled, df_N_sampled]).sort_values('t').reset_index(drop=True)

    X_train = train_df.drop(except_features, axis=1)
    y_train = train_df['class_label'].map(class_mapping).astype(int)  # Encode labels as integers

    xgb = XGBClassifier(
        n_estimators=n_estimators,
        max_depth=2,
        use_label_encoder=False,
        eval_metric='mlogloss',
        random_state=42
    )

    X_train = X_train.fillna(0)
    xgb.fit(X_train, y_train)

    models[ticker_id] = xgb

    validation_set_size = 3 * n_hl
    val_df = df.sample(n=validation_set_size, replace=True, random_state=99)
    X_val = val_df.drop(except_features, axis=1).fillna(0)
    y_val = val_df['class_label'].map(class_mapping).astype(int)  # Encode validation labels

    y_pred = xgb.predict(X_val)

    # Confusion Matrix
    cm = confusion_matrix(y_val, y_pred, labels=[1, 2, 0])
    print(f"Confusion Matrix for Ticker {ticker_id}:\n{cm}\n")

    # Classification Report
    cr = classification_report(y_val, y_pred, labels=[1, 2, 0], target_names=['H', 'L', 'N'])
    print(f"Classification Report for Ticker {ticker_id}:\n{cr}")

    # Balanced Accuracy
    bal_acc = balanced_accuracy_score(y_val, y_pred)
    print(f"Balanced Accuracy for Ticker {ticker_id}: {bal_acc:.4f}\n")


Confusion Matrix for Ticker 1:
[[ 12   0   0]
 [  0   5   0]
 [  7   2 298]]

Classification Report for Ticker 1:
              precision    recall  f1-score   support

           H       0.63      1.00      0.77        12
           L       0.71      1.00      0.83         5
           N       1.00      0.97      0.99       307

    accuracy                           0.97       324
   macro avg       0.78      0.99      0.86       324
weighted avg       0.98      0.97      0.97       324

Balanced Accuracy for Ticker 1: 0.9902

Confusion Matrix for Ticker 2:
[[  5   0   0]
 [  0   4   0]
 [  1   4 238]]

Classification Report for Ticker 2:
              precision    recall  f1-score   support

           H       0.83      1.00      0.91         5
           L       0.50      1.00      0.67         4
           N       1.00      0.98      0.99       243

    accuracy                           0.98       252
   macro avg       0.78      0.99      0.86       252
weighted avg       0.99  

In [19]:
import pandas as pd
import numpy as np
import os

# Load test data
test_df = pd.read_csv('modified_test.csv')

# Create index-to-feature mapping from columns
feature_mapping = {idx: col for idx, col in enumerate(test_df.columns)}

except_features_test = ['id', 'ticker_id', 't']
max_lag = 2

# Define lag feature order (same as training)
lag_feature_order = [col for col in test_df.columns if col not in except_features_test]

# Initialize lag buffers for each ticker_id
lag_buffers = {
    tid: {col: [] for col in lag_feature_order} for tid in range(1, 7)
}

# Assume these are already loaded from training:
# feature_stats = {ticker_id: {'mean': ..., 'std': ...}, ...}
# models = {ticker_id: XGBClassifier trained model, ...}

# Class label mappings
class_mapping = {'N': 0, 'H': 1, 'L': 2}
inverse_class_mapping = {v: k for k, v in class_mapping.items()}

predictions = []

for idx, row in test_df.iterrows():
    ticker = int(row['ticker_id'])
    row_id = row['id']

    if ticker not in models or ticker not in feature_stats:
        print(f"Skipping row id {row_id} due to missing model or stats for ticker {ticker}")
        continue

    stats = feature_stats[ticker]
    model = models[ticker]

    # Scale features with simple mean imputation for missing values
    scaled_row = {}
    for idx_col, col in feature_mapping.items():
        if col not in except_features_test:
            val = row[col]
            mean = stats['mean'].get(col, 0)
            std = stats['std'].get(col, 1)
            if pd.isna(val):
                val = mean
            scaled_row[col] = (val - mean) / std if std != 0 else 0

    # Create lag features
    lag_features = {}
    for col in lag_feature_order:
        for lag in range(1, max_lag + 1):
            if len(lag_buffers[ticker][col]) >= lag:
                lag_features[f'{col}_lag{lag}'] = lag_buffers[ticker][col][-lag]
            else:
                lag_features[f'{col}_lag{lag}'] = 0

    # Prepare input feature vector
    input_features = [scaled_row[col] for col in lag_feature_order]
    input_features += [lag_features[f'{col}_lag{lag}'] for col in lag_feature_order for lag in range(1, max_lag + 1)]

    input_array = np.array(input_features).reshape(1, -1)

    # Predict directly with XGBoost model
    pred_int = model.predict(input_array)[0]
    pred = inverse_class_mapping[pred_int]

    predictions.append({'id': row_id, 'class_label': pred})

    # Update lag buffers
    for col in lag_feature_order:
        lag_buffers[ticker][col].append(scaled_row[col])
        if len(lag_buffers[ticker][col]) > max_lag:
            lag_buffers[ticker][col].pop(0)

# Save predictions to CSV
os.makedirs('predictions', exist_ok=True)
pd.DataFrame(predictions).to_csv('predictions/xgboost_predictions.csv', index=False)
